name: Sync Fork

on:
  push:
    branches:
      - main

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
       
      - name: Push to fork
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.FORK_TOKEN }}
          repository: LeeCh0129/Rolling
          branch: ${{ github.ref_name }}
          force: false